### ISSUE TITLE
broken image link in welcome bot

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-labs#17]
**Description**
Example of the issue - https://github.com/layer5io/service-mesh-labs/pull/13

**Expected Behavior**
Reference needs fixed in https://github.com/layer5io/service-mesh-labs/blob/master/.github/config.yml

**Screenshots**

<img width="1165" alt="Screen Shot 2021-06-09 at 4 42 45 PM" src="https://user-images.githubusercontent.com/7570704/121433549-c7f96680-c941-11eb-9120-577824267c11.png">

**Comment by leecalcote** [comment]
@kaushambisharma can you fix?

**Comment by kaushambisharma** [comment]
Yes
