### ISSUE TITLE
Start all labs with a ready Kubernetes

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-labs#22]
**Current Behavior**

**Desired Behavior**

---
**Resources**

**Alternatives / Additional Context**

**Comment by devansh42** [comment]
#### Current Behaviour
* User needs to install **minikube** in the Katacoda environment before starting the lab.

#### Desired Behaviour
* **minikube** should be pre-installed and user just need to have install **mesheryctl** directly.

**Comment by devansh42** [comment]
Hey @leecalcote , Can you assign this issue to me

**Comment by leecalcote** [comment]
Oh, my goodness. I missed these comments, @devansh42. Your issue description is so much better than mine. ;)

**Comment by suhaniii** [comment]
@leecalcote  consul still using Minikube as backend image, rest have Kubernetes set.

https://github.com/layer5io/service-mesh-labs/blob/master/Meshery-Adapters/consul-meshery-adapter/index.json
