### ISSUE TITLE
[BUG] /root/shell.sh: No such file or directory

### ISSUE THREAD

**Issue by iamsdas** [layer5io/service-mesh-labs#27]
**Description**

Currently when we start any of the labs we get greeted with this error:
```
$ /root/shell.sh
-bash: /root/shell.sh: No such file or directory
```
**Expected Behavior**

Lab starts without any issues

**Screenshots**

![image](https://user-images.githubusercontent.com/26461855/129382750-a5b2f86a-41d8-47c0-8f72-064267c4d6be.png)

**Environment:**
 - OS: Elementary OS 6
 - Browser: Brave
 - Version: 1.28
 - Device:Laptop

**Comment by iamsdas** [comment]
Closing because issue got resolved by itself

**Comment by leecalcote** [comment]
@iamsdas is this still an issue?

**Comment by iamsdas** [comment]
I tried out the labs a few times and could not reproduce the issue. So I think it is safe to assume that it has been fixed. 🚀

**Comment by leecalcote** [comment]
Awesome. Thank you, @iamsdas. 

By the way, we are about to start building a new Meshery adapter for Cilium service mesh. Please check in Slack, if interested to participate in it.
