### ISSUE TITLE
Lab for `Open Service Mesh`

### ISSUE THREAD

**Issue by suhaniii** [layer5io/service-mesh-labs#28]
**Current Behavior**

We don't have scenario for `Open Service Mesh ` under `Meshery-Adapters`

**Desired Behavior**

Create a new scenario under `Meshery-Adapters` for `Open Service Mesh ` 

---
**Resources**

[Sample Lab](https://github.com/layer5io/service-mesh-labs/tree/master/Meshery-Adapters/consul-meshery-adapter)

**Alternatives / Additional Context**

**Comment by Meghana-12** [comment]
Hi, I'd like to work on this.

**Comment by sayantan1413** [comment]
Sure @Meghana-12 go ahead 🎉

**Comment by warunicorn19** [comment]
hey, @Meghana-12 any updates?

**Comment by Meghana-12** [comment]
Hey, sorry need a little more time!

**Comment by warunicorn19** [comment]
Hey @Meghana-12 if you haven't started already, could I do this? I already have a katacoda env. Set from the traefik mesh lab.

**Comment by Meghana-12** [comment]
Sure, go ahead!
