### ISSUE TITLE
Lab for `Traefik Mesh`

### ISSUE THREAD

**Issue by suhaniii** [layer5io/service-mesh-labs#29]
**Current Behavior**

Currently we don't have scenario `Traefik Mesh` under `Meshery-Adapters`

**Desired Behavior**

Create a new scenario under `Meshery-Adapters` for `Traefik Mesh`

---
**Resources**

[Sample Lab](https://github.com/layer5io/service-mesh-labs/tree/master/Meshery-Adapters/consul-meshery-adapter)

**Alternatives / Additional Context**

**Comment by suhaniii** [comment]
@navendu-pottekkat Can you please help me in assigning to right 'Anshuman'

**Comment by navendu-pottekkat** [comment]
Could you ask him to comment here?

**Comment by suhaniii** [comment]
> Could you ask him to comment here?

I don't know full name

**Comment by navendu-pottekkat** [comment]
You can post on Slack and hopes he picks it up?

**Comment by AnshumanDhiman** [comment]
can I work on this issue @suhaniii

**Comment by navendu-pottekkat** [comment]
Assigning to you
