### ISSUE TITLE
Create lab for `Validating Service Mesh Interface Conformance`

### ISSUE THREAD

**Issue by suhaniii** [layer5io/service-mesh-labs#30]
**Current Behavior**

No labs of `Validating Service Mesh Interface Conformance`

**Desired Behavior**

Create lab for `Validating Service Mesh Interface Conformance`

---
**Resources**

Checkout this [PR](https://github.com/meshery/meshery/pull/3865)

**Alternatives / Additional Context**

[Sample Lab](https://github.com/layer5io/service-mesh-labs/tree/master/Meshery-Adapters/consul-meshery-adapter)

**Comment by suhaniii** [comment]
Thank You @sayantan1413 for volunteering 😇

**Comment by warunicorn19** [comment]
@sayantan1413 any updates on this?

**Comment by leecalcote** [comment]
Reopening...
