### ISSUE TITLE
Lab-Website Issue: Instructions not matching with website features

### ISSUE THREAD

**Issue by KerinPithawala** [layer5io/service-mesh-labs#54]
**Description**

In Step 2 of Working with Meshery and Istio lab, the user is asked to select Istio from the management menu on the Meshery site. However, at the moment there is no management menu. 

**Expected Behavior**

Lab documentation has to be updated. Istio should be selected from the Lifestyle menu. 

**Screenshots**

The lab instructions
![image](https://user-images.githubusercontent.com/46436993/147846257-62bbe517-a1d1-4d2d-9957-f000da255ba0.png)

The Meshery site
![image](https://user-images.githubusercontent.com/46436993/147846278-e72b1e67-8a4e-414f-9b99-c90ffac73fb7.png)

**Environment:**
 - OS: Windows
 - Browser: Brave
 - Version: Windows 11
 - Device: Laptop

---
[Optional] **To Reproduce**
1. Go to https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-istio

2. Click on the Start Scenario button. 
![image](https://user-images.githubusercontent.com/46436993/147846337-e3faa214-ce05-4c8a-b46b-5488d52be19f.png)

3. Go to step 2. Scroll down to instructions. 

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
Thank you, @KerinPithawala
