### ISSUE TITLE
"Management" should be changed to "Lifecycle" in the instructions.

### ISSUE THREAD

**Issue by IMPranshu** [layer5io/service-mesh-labs#55]
**Description**

The instructions seem to be wrong as there is no "Management" option to choose from as specified in the instructions.
**Expected Behavior**

Management should change to Lifecycle. There are many instances where an update of the instruction is required.

**Screenshots**

![Screenshot (226)_LI](https://user-images.githubusercontent.com/43396684/147867955-c25a8c52-4a99-411c-9d08-3238f24e67ff.jpg)

https://user-images.githubusercontent.com/43396684/147867979-ef4764a4-10b3-4941-98a1-27f816a98eac.mp4

**Comment by IMPranshu** [comment]
Please assign this to me

**Comment by asubedy** [comment]
@IMPranshu, for now, let's just stick with updating instructions for Consul adapter.

**Comment by IMPranshu** [comment]
Ok, @asubedy I Will update the screenshots and the instruction of the Consul Adapter for this. If I find any other bugs I will open another issue for that

**Comment by asubedy** [comment]
Yep, amazing. The instructions for other adapters are being updated through another PR so, just wanted to make sure we don't duplicate the fix. 😊

**Comment by IMPranshu** [comment]
Yup, cool

**Comment by leecalcote** [comment]
@IMPranshu would you like to do this?

**Comment by IMPranshu** [comment]
Sorry, @leecalcote. I am occupied for the next 12 weeks with a coding competition.

**Comment by leecalcote** [comment]
No sweat. Understood.

@asubedy, a 5 minute update here will knock this out. Will you take it?

**Comment by harshitasao** [comment]
Hi, @leecalcote. You may assign this issue to me if no one else is working. I'll work on it.

**Comment by leecalcote** [comment]
@harshitasao, thank you.

**Comment by asubedy** [comment]
Oops @harshitasao I made a PR for this, required some minor changes. There are instances where the adapter names mismatch on the instruction of NSM and OSM labs, if you would please open an issue for those and start working on those, then it would be great. If you face any doubts feel free to ask me.

**Comment by harshitasao** [comment]
No worries @asubedy , I'll look over the instructions for the lab and make the required issue open.
