### ISSUE TITLE
meshery server cannot connect the traefik-mesh adapter. 

### ISSUE THREAD

**Issue by asubedy** [layer5io/service-mesh-labs#61]
**Description**
The traefik-mesh-adapter is not connected after running the installation command on the lab. The chip does not glow up, and when clicked gives this error

`Could not ping adapter.. To configure an adapter, visit Settings`

This error persists even after all the components are in a ready state when running `mesheryctl system status` command

**Expected Behavior**
The traefik-mesh adapter should be connected after running the installation command

**Screenshots**
![image](https://user-images.githubusercontent.com/51183483/148163418-eb54badd-d9c7-4021-bc09-899ed2238401.png)
![image](https://user-images.githubusercontent.com/51183483/148163431-50ea221e-57c8-41b3-b4c7-2490264d3694.png)

**Environment:**
 - OS: macOS
 - Browser: Brave
 - Version: [e.g. 22]
 - Device: Laptop

---
 **To Reproduce**
1. Go to https://layer5.io/labs
2. Click on `Working with Meshery and Traefik card`
3. Follow the instruction till the installation part
4. Open the Meshery server tab and we can see the `meshery-traefik-mesh` chip not activated.

**Comment by leecalcote** [comment]
@asubedy Will you reconfirm this issue?

**Comment by asubedy** [comment]
Yes @leecalcote the traffic mesh adapter chip is still not glowing 
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/51183483/154851794-7cf42fcf-7d56-4b9a-969d-dc0ca5c17bec.png">
