### ISSUE TITLE
Meshery bash installer incorrect

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-labs#67]
**Description**
From Vaibhav Bisht:

> The curl install url is incorrect.
> currently it is: curl -L https://git.io/meshery | ADAPTERS=istio PLATFORM=kubernetes bash -

**Expected Behavior**
> it should be curl -L https://meshery.io/install | ADAPTERS=istio PLATFORM=kubernetes bash - (edited)

**Comment by vaibhav135** [comment]
Hi,
I would like to work on this.
