### ISSUE TITLE
Not getting kuma versions in the meshery UI and also its not getting installed

### ISSUE THREAD

**Issue by vishal267** [layer5io/service-mesh-labs#7]
**Description**

**Expected Behavior**

**Screenshots**

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by vishal267** [comment]
![image](https://user-images.githubusercontent.com/19798194/110359467-8962c000-8063-11eb-877f-0e14f923f294.png)

**Comment by vishal267** [comment]
![image](https://user-images.githubusercontent.com/19798194/110359606-b2835080-8063-11eb-9f25-eb4b6b0abc44.png)

**Comment by leecalcote** [comment]
@vishal267 thank you for this. I think the issue here is that we have an old screenshot in the labs and that the current state of adapters only provides support for a single version of the service meshes.  // @layer5io/adapter-maintainers

**Comment by vishal267** [comment]
@leecalcote  can i upload/update image directly in the path

**Comment by Aisuko** [comment]
> @leecalcote can i upload/update image directly in the path ?

For sure, we welcome you to do PR at any time.

**Comment by vishal267** [comment]
@Aisuko @leecalcote  please provide the permission to github user - vishal267

git push origin kuma_image
remote: Permission to layer5io/service-mesh-labs.git denied to vishal267

**Comment by leecalcote** [comment]
@vishal267 thanks for contributing here. 👍 You'll want to follow the steps 1 through 9 listed here - https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#building-the-site - in terms of forking, cloning, pushing to your clone then PR'ing from your fork to this repo. There is alternative version of this same flow described in the Meshery repo's contributing.md that might help as well.

**Comment by vishal267** [comment]
@leecalcote PR for same - https://github.com/layer5io/service-mesh-labs/pull/8

**Comment by Aisuko** [comment]
Close due to #8 , thanks @vishal267
