### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/service-mesh-labs#70]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Resources**

**Alternatives / Additional Context**

**Comment by Ghat0tkach** [comment]
> Hi @thisiskaransgit @Ghat0tkach Can you assign me this issue?
> 
> I'm new to open source and might require some guidance (I've checked the explanation of this issue in other issues)

Sure @JapneetRajput  , Here you go!

**Comment by iArchitSharma** [comment]
@JapneetRajput @thisiskaransgit Could I be assigned to this issue if the current assignee is not actively working on it?

**Comment by leecalcote** [comment]
There’s an open PR here…
