### ISSUE TITLE
Each service mesh-specific lab should only load the respective Meshery adapter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/service-mesh-labs#9]
**Description**
Currently, an interactive lab will load all Meshery service mesh adapters even though the lab might be focused on only a single type of service mesh (e.g. Consul).

**Expected Behavior**
Each service mesh-specific lab should only load the respective Meshery adapter for that service mesh.

**Screenshots**
<img width="1551" alt="Screen Shot 2021-05-17 at 4 40 10 PM" src="https://user-images.githubusercontent.com/7570704/118560144-a20be800-b72e-11eb-8d3c-8f83881e11b3.png">

**Comment by kaushambisharma** [comment]
I'd like to work on this issue.

**Comment by leecalcote** [comment]
@kaushambisharma I completely missed your comment until just now... Please fire away.

**Comment by leecalcote** [comment]
@devansh42, it's great to see this thought come forth. Any reason to not extend the current installer to support the use case of more granular choice of adapters? There is general need for this same flexibility beyond the service mesh labs use case.  // @hexxdump @suhaniii

**Comment by leecalcote** [comment]
@devansh42 we're _this_ close... 🙂 Please do take on this issue after your other PR merges.

**Comment by devansh42** [comment]
After merging https://github.com/meshery/meshery/pull/3498 , we can implement the solution.

**Comment by devansh42** [comment]
I think, we should re-open this issue, as labs are not updated with these changes yet, i.e. We still need to update the lab docs as well.

**Comment by navendu-pottekkat** [comment]
Yes we do. GitHub takes the "fixes" keyword seriously. Which is good 😄

**Comment by navendu-pottekkat** [comment]
So to fix this issue, we have to pass in the adapters to the one liner that pulls the shell script.

**Comment by devansh42** [comment]
Yes, I've started working on this issue, will make a PR against it.

**Comment by leecalcote** [comment]
> Yes, I've started working on this issue, will make a PR against it.

You da man.
